packages:
  - apps/*
  - libs/*

catalog:
  '@ai-sdk/google': 2.0.14
  '@daveyplate/better-auth-ui': ^3.1.10
  '@eslint/js': ^9.35.0
  '@modelcontextprotocol/sdk': 1.18.1
  '@tanstack/eslint-config': ^0.3.2
  '@types/better-sqlite3': ^7.6.13
  '@types/cookie': ^1.0.0
  '@types/cookie-parser': ^1.4.9
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.3
  '@types/node': ^24.4.0
  '@types/qs': ^6.14.0
  '@typescript-eslint/eslint-plugin': ^8.43.0
  '@typescript-eslint/parser': ^8.43.0
  ai: 5.0.44
  better-auth: 1.3.11
  better-sqlite3: ^12.2.0
  chalk: ^5.6.2
  cookie: ^1.0.2
  cookie-parser: ^1.4.7
  cors: ^2.8.5
  dotenv: ^16.6.1
  drizzle-kit: ^0.31.4
  drizzle-orm: 0.44.5
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  express: ^5.1.0
  globals: ^16.4.0
  prettier: ^3.6.2
  qs: ^6.14.0
  typescript: ^5.9.2
  zod: 4.1.8

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - unrs-resolver
